[workspace]
members = ["macros"]

[package]
name = "zerialize"
description = "Zero-copy serialization"
version = "0.0.0"
edition = "2024"
rust-version = "1.97"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/cberner/zerialize"
authors = ["Christopher Berner <me@cberner.com>"]

[dependencies]
flatbuffers = "25.12.19"
zerialize-macros = { version = "0.0.0", path = "macros" }

[dev-dependencies]
flatbuffers = "25.12.19"
