[package]
name = "zerialize-macros"
description = "Procedural macros for zerialize"
version = "0.0.0"
edition = "2024"
rust-version = "1.97"
license = "MIT OR Apache-2.0"
repository = "https://github.com/cberner/zerialize"
authors = ["Christopher Berner <me@cberner.com>"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.107"
quote = "1.0.47"
syn = { version = "3.0.3", features = ["full"] }
